export const POLLING_INTERVAL = 5000;

export const FME_FAIL_MESSAGES = ["ABORTED", "FME_FAILURE", "JOB_FAILURE"];

export const FME_SUCCESS_MESSAGES = ["SUCCESS"];

export const FME_DONE_STATUSES = [
  ...FME_FAIL_MESSAGES,
  ...FME_SUCCESS_MESSAGES,
] as const;
