import type { MenuConfig } from "./types";

/**
 * TODO: Replace STUB_AVAILABLE_DOCUMENTS and STUB_FOLDERS with real
 * useDocuments() / useFolders() hooks backed by backend API calls
 * (url_document_list / url_folder_list). No documents endpoint exists yet
 * in apps/admin/src/api/. Track this as a follow-up issue.
 */

export const STUB_AVAILABLE_DOCUMENTS: string[] = [
  "1_1_om_op",
  "1_3_dialog_och_delaktighet",
  "2_1_varbergs_forutsattningar",
  "2_3_mal_och_riktlinjer",
  "2_3_varberg_vaxer_hallbart",
  "3_1_strukturkarta",
  "4_stallningstagande_och_hansyn",
  "4_1_bostader_och_offentlig_service",
  "4_2_natur_parker_vatten",
  "4_3_mobilitet_och_trafik",
  "4_4_naringsliv_och_verksamheter",
  "4_5_arkitektur_kulturmiljo_och_landskapsbild",
  "4_6_miljo_halsa_risk_och_sakerhet",
  "4_7_klimatpavarken_och_klimatanpassning",
  "4_8_energi_och_teknisk_forsorjning",
  "5_mark_och_vattenanvandning",
  "5_1_beskrivningar_av_anvandningar",
  "5_1_riksintressen",
  "6_3_Strategisk_miljobedomning",
  "7_1_planeringsunderlag",
  "7_2_utredningar_och_analyser",
  "8_1_3_kallor",
  "8_Planeringsunderlag",
  "8_1_fordjupad_oversiktsplan_for_varobacka",
  "8_2_fordjupad_oversiktsplan_for_rolfstorp_skallinge",
  "8_3_fordjupad_oversiktsplan_for_veddige",
  "8_4_fordjupad_oversiktsplan_for_tvaaker",
  "8_5_fordjupad_oversiktsplan_for_kungsater",
  "8_6_fordjupad_oversiktsplan_for_stadsomradet",
  "8_7_fordjupad_oversiktsplan_for_norra_kusten",
  "9_1_med_oversiktsplanen_som_grund",
  "9_2_en_ettapvis_utbyggnad",
  "9_3_verktyg_for_genomforander",
  "exempeldokument",
  "exempeldokument2",
];

export const STUB_FOLDERS: string[] = [];

export const STUB_USE_DOCUMENT_FOLDERS = false;

/**
 * Demo menuConfig sourced from apps/legacy/admin/map_1.json (Varberg
 * Översiktsplan). Used as initial data when no menuConfig exists yet so the
 * tree editor shows a realistic nested example instead of an empty state.
 */
export const STUB_MENU_CONFIG: MenuConfig = {
  menu: [
    {
      title: "Mark- och vattenanvändningskarta",
      document: "",
      color: "",
      icon: { materialUiIconName: "map", fontSize: "large" },
      maplink:
        "https://oversiktsplan-utv.varberg.se/#m=map_1&x=150000&y=6341002&z=0&l=1423%2C1450%2C1404%2C1405%2C1406%2C1407%2C1409%2C1410%2C1411%2C1448%2C1437%2C1412&p=documentviewer",
      link: "",
      menu: [],
      expandedSubMenu: false,
    },
    {
      title: "Inledning",
      document: "",
      color: "#c23669",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Vad är en översiktsplan?",
          document: "1_1_om_op",
          color: "#edc3d2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Dialog och delaktighet",
          document: "1_3_dialog_och_delaktighet",
          color: "#edc3d2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
    {
      title: "Utgångspunkter",
      document: "",
      color: "#5b457f",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Varbergs förutsättningar",
          document: "2_1_varbergs_forutsattningar",
          color: "#cec7d9",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Mål",
          document: "2_3_mal_och_riktlinjer",
          color: "#cec7d9",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Planeringsinriktningar",
          document: "2_3_varberg_vaxer_hallbart",
          color: "#cec7d9",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
    {
      title: "Utvecklingsinriktning",
      document: "",
      color: "#007765",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Utvecklingsinriktning",
          document: "3_1_strukturkarta",
          color: "#B2D6D1",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Karta för utvecklingsinriktning",
          document: "",
          color: "#B2D6D1",
          icon: { materialUiIconName: "map", fontSize: "large" },
          maplink:
            "https://oversiktsplan-utv.varberg.se/#m=map_1&x=150000&y=6341002&z=0&l=1423%2C1444%2C1443%2C1445%2C1446%2C1451%2C1412&p=documentviewer",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
    {
      title: "Ställningstaganden och hänsyn",
      document: "4_stallningstagande_och_hansyn",
      color: "#f1c400",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Bebyggelse och offentlig service",
          document: "4_1_bostader_och_offentlig_service",
          color: "#F9E799",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Natur, parker och vatten",
          document: "4_2_natur_parker_vatten",
          color: "#F9E799",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Resor och transporter",
          document: "4_3_mobilitet_och_trafik",
          color: "#F9E799",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Näringsliv och verksamheter",
          document: "4_4_naringsliv_och_verksamheter",
          color: "#F9E799",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Arkitektur, kulturmiljö och landskapsbild",
          document: "4_5_arkitektur_kulturmiljo_och_landskapsbild",
          color: "#F9E799",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Miljö, hälsa, risk och säkerhet",
          document: "4_6_miljo_halsa_risk_och_sakerhet",
          color: "#F9E799",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Klimatpåverkan och klimatanpassning",
          document: "4_7_klimatpavarken_och_klimatanpassning",
          color: "#F9E799",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Energi och teknisk försörjning",
          document: "4_8_energi_och_teknisk_forsorjning",
          color: "#F9E799",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
    {
      title: "Mark- och vattenanvändning",
      document: "5_mark_och_vattenanvandning",
      color: "",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Beskrivningar av användningar",
          document: "5_1_beskrivningar_av_anvandningar",
          color: "",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Mark- och vattenanvändningskarta",
          document: "",
          color: "",
          icon: { materialUiIconName: "map", fontSize: "large" },
          maplink:
            "https://oversiktsplan-utv.varberg.se/#m=map_1&x=150000&y=6341002&z=0&l=1423%2C1450%2C1404%2C1405%2C1406%2C1407%2C1409%2C1410%2C1411%2C1448%2C1437%2C1412&p=documentviewer",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
    {
      title: "Genomförande",
      document: "",
      color: "#00719C",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Med översiktsplanen som grund",
          document: "9_1_med_oversiktsplanen_som_grund",
          color: "#B2D4E1",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "En stegvis utbyggnad",
          document: "9_2_en_ettapvis_utbyggnad",
          color: "#B2D4E1",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Verktyg för genomförande",
          document: "9_3_verktyg_for_genomforander",
          color: "#B2D4E1",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
    {
      title: "Konsekvenser",
      document: "",
      color: "#c63714",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Riksintressen, LIS och andra värden",
          document: "5_1_riksintressen",
          color: "#EEC3B8",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Karta för Riksintressen, LIS och andra värden",
          document: "",
          color: "#EEC3B8",
          icon: { materialUiIconName: "map", fontSize: "large" },
          maplink:
            "https://oversiktsplan-utv.varberg.se/#m=map_1&x=150000&y=6341002&z=0&l=1423%2C1421%2C1422%2C1424%2C1425%2C1449%2C1412&p=documentviewer",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Strategisk miljöbedömning",
          document: "6_3_Strategisk_miljobedomning",
          color: "#EEC3B8",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
    {
      title: "Planeringsunderlag",
      document: "",
      color: "#333333",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Planeringsunderlag",
          document: "7_1_planeringsunderlag",
          color: "#C2C2C2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Särskilda utredningar och analyser",
          document: "7_2_utredningar_och_analyser",
          color: "#C2C2C2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Källor",
          document: "8_1_3_kallor",
          color: "#C2C2C2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
    {
      title: "Fördjupade översiktsplaner",
      document: "8_Planeringsunderlag",
      color: "#C23669",
      icon: { materialUiIconName: "", fontSize: "large" },
      maplink: "",
      link: "",
      menu: [
        {
          title: "Fördjupad översiktsplan för Väröbacka",
          document: "8_1_fordjupad_oversiktsplan_for_varobacka",
          color: "#EDC3D2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Fördjupad översiktsplan för Rolfstorp-Skällinge",
          document: "8_2_fordjupad_oversiktsplan_for_rolfstorp_skallinge",
          color: "#EDC3D2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Fördjupad översiktsplan för Veddige",
          document: "8_3_fordjupad_oversiktsplan_for_veddige",
          color: "#EDC3D2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Fördjupad översiktsplan för Tvååker",
          document: "8_4_fordjupad_oversiktsplan_for_tvaaker",
          color: "#EDC3D2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Fördjupad översiktsplan för Kungsäter",
          document: "8_5_fordjupad_oversiktsplan_for_kungsater",
          color: "#EDC3D2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Fördjupad översiktsplan för Stadsområdet",
          document: "8_6_fordjupad_oversiktsplan_for_stadsomradet",
          color: "#EDC3D2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
        {
          title: "Fördjupad översiktsplan för Norra Kusten",
          document: "8_7_fordjupad_oversiktsplan_for_norra_kusten",
          color: "#EDC3D2",
          icon: { materialUiIconName: "", fontSize: "large" },
          maplink: "",
          link: "",
          menu: [],
          expandedSubMenu: false,
        },
      ],
      expandedSubMenu: false,
    },
  ],
};
